name: CSV Comparison Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run CSV Export & Comparison Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest

      - name: Run pytest and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          report_path: allure-report
          allure_report: true

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
