name: CSV Comparison Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  test:
    name: Run CSV Export & Comparison Tests
    runs-on: ubuntu-latest

    env:
      ALLURE_VERSION: "2.27.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Run all tests and generate Allure results
        run: |
          pytest --alluredir=allure-results --disable-warnings -q
        continue-on-error: true

      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report

      - name: Upload Raw Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-raw-results
          path: allure-results


#name: CSV Comparison Tests
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#permissions:
#  contents: read
#  actions: read
#  id-token: write
#
#jobs:
#  test:
#    name: Run CSV Export & Comparison Tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.11"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pytest allure-pytest playwright
#          playwright install --with-deps
#
#      - name: Run pytest and generate Allure results
#        run: pytest --alluredir=allure-results
#        continue-on-error: true
#
#      - name: Generate Allure HTML Report
#        uses: simple-elf/allure-report-action@v1.7
#        with:
#          results_dir: allure-results
#          report_dir: allure-report
#          clean: true
#
#      - name: Upload Allure HTML Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-html-report
#          path: allure-report
#
#      - name: Upload Raw Allure Results
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-raw-results
#          path: allure-results
